/**
 * FlowAccount Open API
 * FlowAccount.com โปรแกรมบัญชีออนไลน์ใช้งานง่าย สำหรับธุรกิจที่พึ่งเริ่มต้น
 *
 * The version of the OpenAPI document: 2-oas3
 * Contact: developer@flowaccount.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class BusinessCategory {
    /**
    * id of category
    */
    'id'?: number;
    /**
    * system code
    */
    'systemCode'?: number;
    /**
    * id of business category
    */
    'categoryId'?: number;
    /**
    * name local of category
    */
    'categoryNameLocal'?: string;
    /**
    * name foreign of category
    */
    'categoryNameForeign'?: string;
    /**
    * id of debit
    */
    'debitId'?: number;
    /**
    * id of debit category
    */
    'debitCategory'?: number;
    /**
    * code of debit category
    */
    'debitCode'?: string;
    /**
    * name local of debit
    */
    'debitNameLocal'?: string;
    /**
    * name foreign of debit
    */
    'debitNameForeign'?: string;
    /**
    * id of credit
    */
    'creditId'?: number;
    /**
    * id of credit category
    */
    'creditCategory'?: number;
    /**
    * code of credit category
    */
    'creditCode'?: string;
    /**
    * name local of credit
    */
    'creditNameLocal'?: string;
    /**
    * name foreign of credit
    */
    'creditNameForeign'?: string;
    /**
    * keyword
    */
    'keywords'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "systemCode",
            "baseName": "systemCode",
            "type": "number"
        },
        {
            "name": "categoryId",
            "baseName": "categoryId",
            "type": "number"
        },
        {
            "name": "categoryNameLocal",
            "baseName": "categoryNameLocal",
            "type": "string"
        },
        {
            "name": "categoryNameForeign",
            "baseName": "categoryNameForeign",
            "type": "string"
        },
        {
            "name": "debitId",
            "baseName": "debitId",
            "type": "number"
        },
        {
            "name": "debitCategory",
            "baseName": "debitCategory",
            "type": "number"
        },
        {
            "name": "debitCode",
            "baseName": "debitCode",
            "type": "string"
        },
        {
            "name": "debitNameLocal",
            "baseName": "debitNameLocal",
            "type": "string"
        },
        {
            "name": "debitNameForeign",
            "baseName": "debitNameForeign",
            "type": "string"
        },
        {
            "name": "creditId",
            "baseName": "creditId",
            "type": "number"
        },
        {
            "name": "creditCategory",
            "baseName": "creditCategory",
            "type": "number"
        },
        {
            "name": "creditCode",
            "baseName": "creditCode",
            "type": "string"
        },
        {
            "name": "creditNameLocal",
            "baseName": "creditNameLocal",
            "type": "string"
        },
        {
            "name": "creditNameForeign",
            "baseName": "creditNameForeign",
            "type": "string"
        },
        {
            "name": "keywords",
            "baseName": "keywords",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BusinessCategory.attributeTypeMap;
    }
}

