/**
 * FlowAccount Open API
 * FlowAccount.com โปรแกรมบัญชีออนไลน์ใช้งานง่าย สำหรับธุรกิจที่พึ่งเริ่มต้น
 *
 * The version of the OpenAPI document: 2-oas3
 * Contact: developer@flowaccount.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class Document {
    /**
    * รหัส ลูกค้า/ผู้จำหน่าย
    */
    'contactCode'?: string;
    /**
    * ชื่อ ลูกค้า/ผู้จำหน่าย
    */
    'contactName': string;
    /**
    * ที่อยู่ ลูกค้า/ผู้จำหน่าย
    */
    'contactAddress'?: string;
    /**
    * เลขประจำตัวผู้เสียภาษี ลูกค้า/ผู้จำหน่าย
    */
    'contactTaxId'?: string;
    /**
    * สำนักงาน/สาขา
    */
    'contactBranch'?: string;
    /**
    * ชื่อผู้ติดต่อ
    */
    'contactPerson'?: string;
    /**
    * อีเมลผู้ติดต่อ
    */
    'contactEmail'?: string;
    /**
    * เบอร์มือถือผู้ติดต่อ
    */
    'contactNumber'?: string;
    /**
    * รหัสไปรษณีย์ติดต่อ
    */
    'contactZipCode'?: string;
    /**
    * ประผู้ติดต่อ <br> 1 = บุคคลธรรมดา <br> 3 = นิติบุคคล
    */
    'contactGroup'?: number;
    /**
    * วันที่เอกสาร รูปแบบ yyyy-MM-dd
    */
    'publishedOn': string;
    /**
    * รูปแบบเครดิต <br> 1 = เครดิต (วัน) <br> 3 = เงินสด  <br> 5 = เครดิต (ไม่แสดงวันที่ครบกำหนด)
    */
    'creditType'?: number;
    /**
    * จำนวนวันที่ให้เครดิต
    */
    'creditDays'?: number;
    /**
    * วันครบกำหนดเอกสาร รูปแบบ yyyy-MM-dd
    */
    'dueDate': string;
    /**
    * ชื่อผู้สร้างเอกสาร หรือ ชื่อพนักงานขาย
    */
    'salesName'?: string;
    /**
    * ชื่อโปรเจค
    */
    'projectName'?: string;
    /**
    * เลขที่อ้างอิง หรือ เลขที่เอกสารที่เกี่ยวข้อง
    */
    'reference'?: string;
    /**
    * มูลค่าเอกสารรวมภาษีแล้วหรือไม่
    */
    'isVatInclusive'?: boolean;
    /**
    * มูลค่ารวมเป็นเงิน
    */
    'subTotal'?: number;
    /**
    * มูลค่าส่วนลดเป็นเปอร์เซ็นต์
    */
    'discountPercentage'?: number;
    /**
    * มูลค่าส่วนลดเป็นจำนวน (บาท)
    */
    'discountAmount'?: number;
    /**
    * มูลค่าหลังหักส่วนลด
    */
    'totalAfterDiscount': number;
    /**
    * มูลค่าหลังหักส่วนลด มีภาษีมูลค่าเพิ่ม 7%
    */
    'isVat'?: boolean;
    /**
    * ภาษีมูลค่าเพิ่ม
    */
    'vatAmount'?: number;
    /**
    * จำนวนเงินรวมทั้งสิ้น (รวมภาษีมูลค่าเพิ่ม 7% แล้ว)
    */
    'grandTotal': number;
    /**
    * แสดงหรือไม่แสดง หัก ณ ที่จ่ายท้ายเอกสาร
    */
    'documentShowWithholdingTax'?: boolean;
    /**
    * ภาษี ณ ที่จ่าย (%)
    */
    'documentWithholdingTaxPercentage'?: number;
    /**
    * หมายเหตุเอกสาร
    */
    'remarks'?: string;
    /**
    * โน๊ตภายในบริษัท
    */
    'internalNotes'?: string;
    /**
    * ลายเซ็นอิเล็กทรอนิกส์และตรายาง
    */
    'showSignatureOrStamp'?: boolean;
    'documentStructureType': string;

    static discriminator: string | undefined = "documentStructureType";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "contactCode",
            "baseName": "contactCode",
            "type": "string"
        },
        {
            "name": "contactName",
            "baseName": "contactName",
            "type": "string"
        },
        {
            "name": "contactAddress",
            "baseName": "contactAddress",
            "type": "string"
        },
        {
            "name": "contactTaxId",
            "baseName": "contactTaxId",
            "type": "string"
        },
        {
            "name": "contactBranch",
            "baseName": "contactBranch",
            "type": "string"
        },
        {
            "name": "contactPerson",
            "baseName": "contactPerson",
            "type": "string"
        },
        {
            "name": "contactEmail",
            "baseName": "contactEmail",
            "type": "string"
        },
        {
            "name": "contactNumber",
            "baseName": "contactNumber",
            "type": "string"
        },
        {
            "name": "contactZipCode",
            "baseName": "contactZipCode",
            "type": "string"
        },
        {
            "name": "contactGroup",
            "baseName": "contactGroup",
            "type": "number"
        },
        {
            "name": "publishedOn",
            "baseName": "publishedOn",
            "type": "string"
        },
        {
            "name": "creditType",
            "baseName": "creditType",
            "type": "number"
        },
        {
            "name": "creditDays",
            "baseName": "creditDays",
            "type": "number"
        },
        {
            "name": "dueDate",
            "baseName": "dueDate",
            "type": "string"
        },
        {
            "name": "salesName",
            "baseName": "salesName",
            "type": "string"
        },
        {
            "name": "projectName",
            "baseName": "projectName",
            "type": "string"
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string"
        },
        {
            "name": "isVatInclusive",
            "baseName": "isVatInclusive",
            "type": "boolean"
        },
        {
            "name": "subTotal",
            "baseName": "subTotal",
            "type": "number"
        },
        {
            "name": "discountPercentage",
            "baseName": "discountPercentage",
            "type": "number"
        },
        {
            "name": "discountAmount",
            "baseName": "discountAmount",
            "type": "number"
        },
        {
            "name": "totalAfterDiscount",
            "baseName": "totalAfterDiscount",
            "type": "number"
        },
        {
            "name": "isVat",
            "baseName": "isVat",
            "type": "boolean"
        },
        {
            "name": "vatAmount",
            "baseName": "vatAmount",
            "type": "number"
        },
        {
            "name": "grandTotal",
            "baseName": "grandTotal",
            "type": "number"
        },
        {
            "name": "documentShowWithholdingTax",
            "baseName": "documentShowWithholdingTax",
            "type": "boolean"
        },
        {
            "name": "documentWithholdingTaxPercentage",
            "baseName": "documentWithholdingTaxPercentage",
            "type": "number"
        },
        {
            "name": "remarks",
            "baseName": "remarks",
            "type": "string"
        },
        {
            "name": "internalNotes",
            "baseName": "internalNotes",
            "type": "string"
        },
        {
            "name": "showSignatureOrStamp",
            "baseName": "showSignatureOrStamp",
            "type": "boolean"
        },
        {
            "name": "documentStructureType",
            "baseName": "documentStructureType",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Document.attributeTypeMap;
    }
}

