/**
 * FlowAccount Open API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class Document {
    /**
    * เลขที่เอกสาร
    */
    'documentSerial'?: string;
    /**
    * รหัส ผู้ติดต่อ/ผู้จำหน่าย
    */
    'contactCode'?: string;
    /**
    * ชื่อบริษัท
    */
    'contactName': string;
    /**
    * ที่อยู่ ผู้ติดต่อ/ผู้จำหน่าย
    */
    'contactAddress'?: string;
    /**
    * เลขประจำตัวผู้เสียภาษี ผู้ติิดต่อ/ผู้จำหน่าย
    */
    'contactTaxId'?: string;
    /**
    * สำนักงาน/สาขา
    */
    'contactBranch'?: string;
    /**
    * ชื่อผู้ติดต่อ
    */
    'contactPerson'?: string;
    /**
    * อีเมลผู้ติดต่อ
    */
    'contactEmail'?: string;
    /**
    * เบอร์มือถือผู้ติดต่อ
    */
    'contactNumber'?: string;
    /**
    * รหัสไปรษณีย์ติดต่อ
    */
    'contactZipCode'?: string;
    /**
    * วันที่เอกสาร รูปแบบ yyyy-MM-dd
    */
    'publishedOn': string;
    /**
    * วันครบกำหนดเอกสาร รูปแบบ yyyy-MM-dd
    */
    'dueDate'?: string;
    /**
    * ชื่อโปรเจค
    */
    'projectName'?: string;
    /**
    * เลขที่อ้างอิง
    */
    'reference'?: string;
    /**
    * มูลค่าเอกสารรวมภาษีแล้วหรือไม่
    */
    'isVatInclusive'?: boolean;
    /**
    * none=0, percent=1, value=3
    */
    'discountType'?: number;
    /**
    * Value of discount by percentage
    */
    'discountPercentage'?: number;
    /**
    * Value of discount by amount
    */
    'discountAmount'?: number;
    /**
    * Document creator or sale name
    */
    'salesName'?: string;
    /**
    * Total price of document
    */
    'subTotal'?: number;
    /**
    * มูลค่าหลังหักส่วนลด
    */
    'totalAfterDiscount': number;
    /**
    * มูลค่าท้ายเอกสาร (รวม vat เสมอ)
    */
    'grandTotal': number;
    /**
    * มูลค่าเอกสารก่อนภาษี
    */
    'totalWithoutVat'?: number;
    /**
    * ภาษีมูลค่าเพิ่ม
    */
    'vatAmount'?: number;
    'remarks'?: string;
    /**
    * โน๊ตภายในบริษัท
    */
    'internalNotes'?: string;
    /**
    * None=0, Cash=1, Transfer=5,CreditCard=7
    */
    'paymentMethod'?: number;
    /**
    * วันที่รับชำระเงิน รูปแบบ yyyy-MM-dd
    */
    'paymentDate'?: string;
    /**
    * รายละเอียดการเก็บเงิน
    */
    'paymentRemarks'?: string;
    /**
    * ชื่อธนาคาร
    */
    'bankAccountName'?: string;
    /**
    * เลขที่ธนาคาร/บัตรเคดิต(สำหรับ MethodPayment=5,7)
    */
    'bankAccountNumber'?: string;
    /**
    * จำนวนเงินที่เก็บ
    */
    'collected'?: number;
    /**
    * ยอดหัก ณ ที่จ่าย
    */
    'withheldAmount'?: number;
    /**
    * หัก ณ ที่จ่าย
    */
    'withheldPercentage'?: number;
    /**
    * ค่าธรรมเนียม
    */
    'fee'?: number;
    /**
    * แสดงหรือไแสดง หักณที่จ่ายท้ายบิล
    */
    'documentShowWithholdingTax'?: boolean;
    /**
    * มูลค่าภาษีหักณที่จ่าย
    */
    'documentWithholdingTaxAmount'?: number;
    /**
    * ภาษี ณ ที่จ่าย (%)
    */
    'documentWithholdingTaxPercentage'?: number;
    /**
    * จำนวนวันที่ให้เครดิต
    */
    'creditDays'?: number;
    /**
    * รูปแบบเครดิต: 1 = เครดิต (วัน) / 5 = เครดิต (ไม่แสดงวันที่ครบกำหนด)
    */
    'creditType'?: number;
    /**
    * id ของเอกสาร
    */
    'recordId'?: number;
    'documentStructureType': string;

    static discriminator: string | undefined = "documentStructureType";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "documentSerial",
            "baseName": "documentSerial",
            "type": "string"
        },
        {
            "name": "contactCode",
            "baseName": "contactCode",
            "type": "string"
        },
        {
            "name": "contactName",
            "baseName": "contactName",
            "type": "string"
        },
        {
            "name": "contactAddress",
            "baseName": "contactAddress",
            "type": "string"
        },
        {
            "name": "contactTaxId",
            "baseName": "contactTaxId",
            "type": "string"
        },
        {
            "name": "contactBranch",
            "baseName": "contactBranch",
            "type": "string"
        },
        {
            "name": "contactPerson",
            "baseName": "contactPerson",
            "type": "string"
        },
        {
            "name": "contactEmail",
            "baseName": "contactEmail",
            "type": "string"
        },
        {
            "name": "contactNumber",
            "baseName": "contactNumber",
            "type": "string"
        },
        {
            "name": "contactZipCode",
            "baseName": "contactZipCode",
            "type": "string"
        },
        {
            "name": "publishedOn",
            "baseName": "publishedOn",
            "type": "string"
        },
        {
            "name": "dueDate",
            "baseName": "dueDate",
            "type": "string"
        },
        {
            "name": "projectName",
            "baseName": "projectName",
            "type": "string"
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string"
        },
        {
            "name": "isVatInclusive",
            "baseName": "isVatInclusive",
            "type": "boolean"
        },
        {
            "name": "discountType",
            "baseName": "discountType",
            "type": "number"
        },
        {
            "name": "discountPercentage",
            "baseName": "discountPercentage",
            "type": "number"
        },
        {
            "name": "discountAmount",
            "baseName": "discountAmount",
            "type": "number"
        },
        {
            "name": "salesName",
            "baseName": "salesName",
            "type": "string"
        },
        {
            "name": "subTotal",
            "baseName": "subTotal",
            "type": "number"
        },
        {
            "name": "totalAfterDiscount",
            "baseName": "totalAfterDiscount",
            "type": "number"
        },
        {
            "name": "grandTotal",
            "baseName": "grandTotal",
            "type": "number"
        },
        {
            "name": "totalWithoutVat",
            "baseName": "totalWithoutVat",
            "type": "number"
        },
        {
            "name": "vatAmount",
            "baseName": "vatAmount",
            "type": "number"
        },
        {
            "name": "remarks",
            "baseName": "remarks",
            "type": "string"
        },
        {
            "name": "internalNotes",
            "baseName": "internalNotes",
            "type": "string"
        },
        {
            "name": "paymentMethod",
            "baseName": "paymentMethod",
            "type": "number"
        },
        {
            "name": "paymentDate",
            "baseName": "paymentDate",
            "type": "string"
        },
        {
            "name": "paymentRemarks",
            "baseName": "paymentRemarks",
            "type": "string"
        },
        {
            "name": "bankAccountName",
            "baseName": "bankAccountName",
            "type": "string"
        },
        {
            "name": "bankAccountNumber",
            "baseName": "bankAccountNumber",
            "type": "string"
        },
        {
            "name": "collected",
            "baseName": "collected",
            "type": "number"
        },
        {
            "name": "withheldAmount",
            "baseName": "withheldAmount",
            "type": "number"
        },
        {
            "name": "withheldPercentage",
            "baseName": "withheldPercentage",
            "type": "number"
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "number"
        },
        {
            "name": "documentShowWithholdingTax",
            "baseName": "documentShowWithholdingTax",
            "type": "boolean"
        },
        {
            "name": "documentWithholdingTaxAmount",
            "baseName": "documentWithholdingTaxAmount",
            "type": "number"
        },
        {
            "name": "documentWithholdingTaxPercentage",
            "baseName": "documentWithholdingTaxPercentage",
            "type": "number"
        },
        {
            "name": "creditDays",
            "baseName": "creditDays",
            "type": "number"
        },
        {
            "name": "creditType",
            "baseName": "creditType",
            "type": "number"
        },
        {
            "name": "recordId",
            "baseName": "recordId",
            "type": "number"
        },
        {
            "name": "documentStructureType",
            "baseName": "documentStructureType",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Document.attributeTypeMap;
    }
}

