/**
 * FlowAccount Open API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineProductItem } from './inlineProductItem';

export class InlineDocumentAllOf {
    'items'?: Array<InlineProductItem>;
    /**
    * ใช้ inline แวทหรือไม่
    */
    'useInlineVat'?: boolean;
    /**
    * ยอดขายที่ยกเว้นภาษีมูลค่าเพิ่ม
    */
    'exemptAmount'?: number;
    /**
    * ยอดขายที่คิดภาษีมูลค่าเพิ่ม
    */
    'vatableAmount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<InlineProductItem>"
        },
        {
            "name": "useInlineVat",
            "baseName": "useInlineVat",
            "type": "boolean"
        },
        {
            "name": "exemptAmount",
            "baseName": "exemptAmount",
            "type": "number"
        },
        {
            "name": "vatableAmount",
            "baseName": "vatableAmount",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return InlineDocumentAllOf.attributeTypeMap;
    }
}

