/**
 * FlowAccount Open API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineProductItemAllOf } from './inlineProductItemAllOf';
import { ProductItem } from './productItem';

export class InlineProductItem extends ProductItem {
    /**
    * ส่วนลดสินค้า (%)
    */
    'discountAmountPercentage'?: number;
    /**
    * ส่วนลดสินค้า
    */
    'discountAmount'?: number;
    /**
    * ภาษี
    */
    'vatRate'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "discountAmountPercentage",
            "baseName": "discountAmountPercentage",
            "type": "number"
        },
        {
            "name": "discountAmount",
            "baseName": "discountAmount",
            "type": "number"
        },
        {
            "name": "vatRate",
            "baseName": "vatRate",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(InlineProductItem.attributeTypeMap);
    }
}

