/**
 * FlowAccount Open API
 * FlowAccount.com โปรแกรมบัญชีออนไลน์ใช้งานง่าย สำหรับธุรกิจที่พึ่งเริ่มต้น
 *
 * The version of the OpenAPI document: 2-oas3
 * Contact: developer@flowaccount.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentResponse } from './documentResponse';
import { InlineDocument } from './inlineDocument';
import { InlineDocumentResponseAllOf } from './inlineDocumentResponseAllOf';
import { StatusResponse } from './statusResponse';

export class InlineDocumentResponse extends DocumentResponse {
    'data'?: object & InlineDocument & StatusResponse;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "object & InlineDocument & StatusResponse"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(InlineDocumentResponse.attributeTypeMap);
    }
}

