/**
 * FlowAccount Open API
 * FlowAccount.com โปรแกรมบัญชีออนไลน์ใช้งานง่าย สำหรับธุรกิจที่พึ่งเริ่มต้น
 *
 * The version of the OpenAPI document: 2-oas3
 * Contact: developer@flowaccount.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class PaymentDocumentResponse {
    /**
    * id ของเอกสาร
    */
    'documentId'?: number;
    /**
    * วันที่รับชำระเงิน รูปแบบ yyyy-MM-dd
    */
    'paymentDate'?: string;
    /**
    * จำนวนเงินยอดรับสุทธิ
    */
    'collected'?: number;
    /**
    * ประเภทรายการปรับลด 1 = ส่วนลดพิเศษ / 3 = ค่านายหน้าและส่วนแบ่งการขาย / 5 = ค่าดำเนินการ / 7 = ปัดเศษ <br> (เฉพาะเอกสารใบกำกับภาษี/ใบเสร็จรับเงิน)
    */
    'paymentDeductionType'?: number;
    /**
    * จำนวนเงินยอดรายการปรับลด <br> (เฉพาะเอกสารใบกำกับภาษี/ใบเสร็จรับเงิน)
    */
    'deductionAmount'?: number;
    /**
    * เปอร์เซ็น หัก ณ ที่จ่าย
    */
    'withheldPercentage'?: number;
    /**
    * จำนวน ยอดหัก ณ ที่จ่าย
    */
    'withheldAmount'?: number;
    /**
    * ค่าธรรมเนียม ที่ชำระโดยการโอนเงิน หรือ เช็ค <br> (เฉพาะเอกสารค่าใช้จ่าย)
    */
    'charge'?: number;
    /**
    * วิธีการชำระ 1 = เงินสด / 3 = เช็ค /  5 = โอนเงิน , 7 = เครดิต
    */
    'paymentMethod'?: number;
    /**
    * ช่องทางการชำระเงิน
    */
    'paymentChannel'?: string;
    /**
    * รายละเอียดการเก็บเงิน
    */
    'paymentRemarks'?: string;
    /**
    * ชื่อธนาคาร
    */
    'bankAccountName'?: string;
    /**
    * เลขที่ธนาคาร / บัตรเคดิต
    */
    'bankAccountNumber'?: string;
    /**
    * วันที่หน้าเช็ค รูปแบบ yyyy-MM-dd
    */
    'chequeDate'?: string;
    /**
    * เลขที่เช็คธนาคาร
    */
    'chequeNumber'?: string;
    /**
    * ธนาคารที่ระบุหน้าเช็ค <br> 1 = ธนาคารกรุงเทพ <br> 2 = ธนาคารกสิกรไทย <br> 3 = ธนาคารกรุงไทย <br> 4 = ธนาคารทหารไทย <br> 5 = ธนาคารไทยพาณิชย์ <br> 6 = ธนาคารสแตนดาร์ดชาร์เตอร์ด <br> 7 = ธนาคารซีไอเอ็มบี ไทย <br> 8 = ธนาคารยูโอบี <br> 10 = ธนาคารกรุงศรีอยุธยา <br> 11 = ธนาคารออมสิน <br> 12 = ธนาคารธนชาต <br> 13 = ธนาคารแลนด์ แอนด์ เฮ้าส์ <br> 14 = ธนาคารเกียรตินาคิน <br> 15 = ธนาคารซิตี้แบงก์ <br> 16 = ธนาคารทิสโก้ <br> 53 = ธนาคารเพื่อการเกษตรและสหกรณ์การเกษตร <br> 54 = ธนาคารเพื่อการส่งออกและนำเข้าแห่งประเทศไทย <br> 55 = ธนาคารอาคารสงเคราะห์ <br> 56 = ธนาคารพัฒนาวิสาหกิจขนาดกลางและขนาดย่อมแห่งประเทศไทย <br> 57 = ธนาคารอิสลามแห่งประเทศไทย <br> 58 = ธนาคารแห่งประเทศจีน (ไทย) <br> 59 = ธนาคารไอซีบีซี (ไทย) <br> 60 = ธนาคารเมกะ สากลพาณิชย์ <br> 61 = ธนาคารซูมิโตโม มิตซุย แบงกิ้ง คอร์ปอเรชั่น <br> 62 = ธนาคารมิซูโฮ จำกัด (กรุงเทพฯ) <br> 63 = ธนาคารฮ่องกงและเซี่ยงไฮ้แบงกิ้งคอร์ปอเรชั่น <br> 64 = ธนาคารไทยเครดิต เพื่อรายย่อย 
    */
    'chequeBankAccountId'?: number;
    /**
    * ธนาคารที่ชำระด้วยบัตรเครดิต <br> 1 = ธนาคารกรุงเทพ <br> 2 = ธนาคารกสิกรไทย <br> 3 = ธนาคารกรุงไทย <br> 4 = ธนาคารทหารไทย <br> 5 = ธนาคารไทยพาณิชย์ <br> 6 = ธนาคารสแตนดาร์ดชาร์เตอร์ด <br> 7 = ธนาคารซีไอเอ็มบี ไทย <br> 8 = ธนาคารยูโอบี <br> 10 = ธนาคารกรุงศรีอยุธยา <br> 11 = ธนาคารออมสิน <br> 12 = ธนาคารธนชาต <br> 13 = ธนาคารแลนด์ แอนด์ เฮ้าส์ <br> 14 = ธนาคารเกียรตินาคิน <br> 15 = ธนาคารซิตี้แบงก์ <br> 16 = ธนาคารทิสโก้ <br> 53 = ธนาคารเพื่อการเกษตรและสหกรณ์การเกษตร <br> 54 = ธนาคารเพื่อการส่งออกและนำเข้าแห่งประเทศไทย <br> 55 = ธนาคารอาคารสงเคราะห์ <br> 56 = ธนาคารพัฒนาวิสาหกิจขนาดกลางและขนาดย่อมแห่งประเทศไทย <br> 57 = ธนาคารอิสลามแห่งประเทศไทย <br> 58 = ธนาคารแห่งประเทศจีน (ไทย) <br> 59 = ธนาคารไอซีบีซี (ไทย) <br> 60 = ธนาคารเมกะ สากลพาณิชย์ <br> 61 = ธนาคารซูมิโตโม มิตซุย แบงกิ้ง คอร์ปอเรชั่น <br> 62 = ธนาคารมิซูโฮ จำกัด (กรุงเทพฯ) <br> 63 = ธนาคารฮ่องกงและเซี่ยงไฮ้แบงกิ้งคอร์ปอเรชั่น <br> 64 = ธนาคารไทยเครดิต เพื่อรายย่อย 
    */
    'creditCardBankAccountId'?: number;
    /**
    * หมายเหตุ การรับชำระเงิน หรือ จ่ายเงิน
    */
    'remarks'?: string;
    /**
    * สาเหตุเงินขาด เงินเกิน: 51 = เงินขาดหรือเงินกิน / 55 = ค่าธรรมเนียมธนาคาร 
    */
    'remainingCollectedType'?: number;
    /**
    * จำนวน ยอดเงินขาด หรือ เงินเกิน
    */
    'remainingCollected'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "number"
        },
        {
            "name": "paymentDate",
            "baseName": "paymentDate",
            "type": "string"
        },
        {
            "name": "collected",
            "baseName": "collected",
            "type": "number"
        },
        {
            "name": "paymentDeductionType",
            "baseName": "paymentDeductionType",
            "type": "number"
        },
        {
            "name": "deductionAmount",
            "baseName": "deductionAmount",
            "type": "number"
        },
        {
            "name": "withheldPercentage",
            "baseName": "withheldPercentage",
            "type": "number"
        },
        {
            "name": "withheldAmount",
            "baseName": "withheldAmount",
            "type": "number"
        },
        {
            "name": "charge",
            "baseName": "charge",
            "type": "number"
        },
        {
            "name": "paymentMethod",
            "baseName": "paymentMethod",
            "type": "number"
        },
        {
            "name": "paymentChannel",
            "baseName": "paymentChannel",
            "type": "string"
        },
        {
            "name": "paymentRemarks",
            "baseName": "paymentRemarks",
            "type": "string"
        },
        {
            "name": "bankAccountName",
            "baseName": "bankAccountName",
            "type": "string"
        },
        {
            "name": "bankAccountNumber",
            "baseName": "bankAccountNumber",
            "type": "string"
        },
        {
            "name": "chequeDate",
            "baseName": "chequeDate",
            "type": "string"
        },
        {
            "name": "chequeNumber",
            "baseName": "chequeNumber",
            "type": "string"
        },
        {
            "name": "chequeBankAccountId",
            "baseName": "chequeBankAccountId",
            "type": "number"
        },
        {
            "name": "creditCardBankAccountId",
            "baseName": "creditCardBankAccountId",
            "type": "number"
        },
        {
            "name": "remarks",
            "baseName": "remarks",
            "type": "string"
        },
        {
            "name": "remainingCollectedType",
            "baseName": "remainingCollectedType",
            "type": "number"
        },
        {
            "name": "remainingCollected",
            "baseName": "remainingCollected",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return PaymentDocumentResponse.attributeTypeMap;
    }
}

