/**
 * FlowAccount Open API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ProductItem {
    'documentStructureType': string;
    /**
    * service=1, productWithoutStock=3, productWithStock=5
    */
    'type'?: number;
    /**
    * ชื่อสินค้า
    */
    'name': string;
    /**
    * รายละเอียดสินค้า
    */
    'description'?: string;
    /**
    * จำนวนสินค้า
    */
    'quantity': number;
    /**
    * หน่วยสินค้า
    */
    'unitName'?: string;
    /**
    * ราคาสินค้าต่อหน่วย
    */
    'pricePerUnit': number;
    /**
    * ราคารวมสินค้า
    */
    'total': number;

    static discriminator: string | undefined = "documentStructureType";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "documentStructureType",
            "baseName": "documentStructureType",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "unitName",
            "baseName": "unitName",
            "type": "string"
        },
        {
            "name": "pricePerUnit",
            "baseName": "pricePerUnit",
            "type": "number"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ProductItem.attributeTypeMap;
    }
}

