/**
 * FlowAccount Open API
 * FlowAccount.com โปรแกรมบัญชีออนไลน์ใช้งานง่าย สำหรับธุรกิจที่พึ่งเริ่มต้น
 *
 * The version of the OpenAPI document: 2-oas3
 * Contact: developer@flowaccount.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class SendEmailResponse {
    /**
    * Email sent successfully
    */
    'message'?: string;
    /**
    * Status
    */
    'ok'?: boolean;
    /**
    * Change Status Complete
    */
    'successMsg'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "ok",
            "baseName": "ok",
            "type": "boolean"
        },
        {
            "name": "successMsg",
            "baseName": "successMsg",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SendEmailResponse.attributeTypeMap;
    }
}

