/**
 * FlowAccount Open API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class SendEmail {
    /**
    * id เอกสาร (recordId)
    */
    'documentId': number;
    /**
    * ใส่อีเมลผู้ส่ง
    */
    'fromemail': string;
    /**
    * ใส่อีเมลผู้รับ
    */
    'toemail': string;
    /**
    * ส่งสำเนาหาตนเอง
    */
    'cCMyself'?: boolean;
    /**
    * สำเนา (CC)
    */
    'ccEmail'?: string;
    /**
    * สำเนาลับ (BCC)
    */
    'bccEmail'?: string;
    /**
    * หัวข้อ / ชื่อเรื่อง 
    */
    'subject': string;
    /**
    * ข้อความ
    */
    'message'?: string;

    static discriminator: string | undefined = "documentStructureType";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "number"
        },
        {
            "name": "fromemail",
            "baseName": "fromemail",
            "type": "string"
        },
        {
            "name": "toemail",
            "baseName": "toemail",
            "type": "string"
        },
        {
            "name": "cCMyself",
            "baseName": "cCMyself",
            "type": "boolean"
        },
        {
            "name": "ccEmail",
            "baseName": "ccEmail",
            "type": "string"
        },
        {
            "name": "bccEmail",
            "baseName": "bccEmail",
            "type": "string"
        },
        {
            "name": "subject",
            "baseName": "subject",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SendEmail.attributeTypeMap;
    }
}

