/**
 * FlowAccount Open API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentResponse } from './documentResponse';
import { SimpleDocument } from './simpleDocument';
import { SimpleDocumentResponseAllOf } from './simpleDocumentResponseAllOf';

export class SimpleDocumentResponse extends DocumentResponse {
    'data'?: SimpleDocument;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "SimpleDocument"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(SimpleDocumentResponse.attributeTypeMap);
    }
}

