/**
 * FlowAccount Open API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Document } from './document';
import { SimpleDocumentAllOf } from './simpleDocumentAllOf';
import { SimpleProductItem } from './simpleProductItem';
import { UpgradeDocument } from './upgradeDocument';

export class SimpleDocument extends Document {
    'items'?: Array<SimpleProductItem>;
    'documentReferences'?: Array<UpgradeDocument>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<SimpleProductItem>"
        },
        {
            "name": "documentReferences",
            "baseName": "documentReferences",
            "type": "Array<UpgradeDocument>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(SimpleDocument.attributeTypeMap);
    }
}

