/**
 * FlowAccount Open API
 * FlowAccount.com โปรแกรมบัญชีออนไลน์ใช้งานง่าย สำหรับธุรกิจที่พึ่งเริ่มต้น
 *
 * The version of the OpenAPI document: 2-oas3
 * Contact: developer@flowaccount.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReferencedByMe } from './referencedByMe';
import { ReferencedToMe } from './referencedToMe';

export class StatusResponse {
    /**
    * ID เอกสารฉบับนี้
    */
    'recordId'?: number;
    /**
    * ข้อมูลเอกสารปลายทางอ้างอิง ถึง เอกสารฉบับนี้
    */
    'referencedToMe'?: Array<ReferencedToMe>;
    /**
    * ข้อมูลเอกสารต้นทางอ้างอิง ถึง เอกสารฉบับนี้
    */
    'referencedByMe'?: Array<ReferencedByMe>;
    /**
    * เลขสถานะเอกสารฉบับนี้
    */
    'status'?: number;
    /**
    * ชื่อสถานะเอกสารฉบับนี้
    */
    'statusString'?: number;
    /**
    * เลขประเภทเอกสารฉบับนี้
    */
    'documentType'?: number;
    /**
    * สามารถลบเอกสาร :<br> true = ลบได้ <br> false = ลบไม่ได้
    */
    'allowDelete'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "recordId",
            "baseName": "recordId",
            "type": "number"
        },
        {
            "name": "referencedToMe",
            "baseName": "referencedToMe",
            "type": "Array<ReferencedToMe>"
        },
        {
            "name": "referencedByMe",
            "baseName": "referencedByMe",
            "type": "Array<ReferencedByMe>"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number"
        },
        {
            "name": "statusString",
            "baseName": "statusString",
            "type": "number"
        },
        {
            "name": "documentType",
            "baseName": "documentType",
            "type": "number"
        },
        {
            "name": "allowDelete",
            "baseName": "allowDelete",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return StatusResponse.attributeTypeMap;
    }
}

