/**
 * FlowAccount Open API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* ใช้เมื่อต้องการ Upgrade เอกสาร Quotations เป็น เอกสาร Billing Notes
*/
export class UpgradeDocument {
    /**
    * id ของเอกสารต้นทาง
    */
    'recordId': number;
    /**
    * เลขที่เอกสารต้นทาง
    */
    'referenceDocumentSerial': string;
    /**
    * เลขประเภทของเอกสารต้นทาง <br> Quotaions = 3 <br> Billing Notes = 5 <br> Tax Invoices = 7
    */
    'referenceDocumentType': number;

    static discriminator: string | undefined = "documentStructureType";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "recordId",
            "baseName": "recordId",
            "type": "number"
        },
        {
            "name": "referenceDocumentSerial",
            "baseName": "referenceDocumentSerial",
            "type": "string"
        },
        {
            "name": "referenceDocumentType",
            "baseName": "referenceDocumentType",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return UpgradeDocument.attributeTypeMap;
    }
}

